# Generated by Django 5.1.7 on 2025-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='server',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='data_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='error',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='server',
            name='network_speed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='provider',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='public_ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
    ]
