# Generated by Django 5.1.7 on 2025-03-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='output',
            field=models.TextField(default=0, max_length=1023),
            preserve_default=False,
        ),
    ]
