# Generated by Django 5.1.7 on 2025-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_job_eta_job_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.TextField(max_length=1023, null=True),
        ),
    ]
