# Generated by Django 5.1.7 on 2025-03-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_alter_job_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eta',
            field=models.IntegerField(null=True),
        ),
    ]
