# Generated by Django 5.1.7 on 2025-03-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
