# Generated by Django 5.1.7 on 2025-03-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_job_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eta',
            field=models.IntegerField(null=True),
        ),
    ]
