# Generated by Django 5.1.7 on 2025-03-15 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_alter_job_eta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.CharField(choices=[('sync/copy', 'copy')], max_length=127)),
                ('dstFs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dstFs', to='sync.remote')),
                ('srcFs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srcFs', to='sync.remote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sync.task'),
            preserve_default=False,
        ),
    ]
