# Generated by Django 5.1.7 on 2025-03-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_task_job_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.task'),
        ),
    ]
