# Generated by Django 5.1.7 on 2025-03-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_alter_job_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cron',
            field=models.CharField(default='0 */8 * * *', max_length=127),
            preserve_default=False,
        ),
    ]
