# Generated by Django 5.1.7 on 2025-03-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_task_cron'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='type',
            field=models.CharField(choices=[('s3', 'S3')], default='s3', max_length=127),
            preserve_default=False,
        ),
    ]
