# Generated by Django 5.1.7 on 2025-03-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0012_remote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='remote',
            name='name',
            field=models.CharField(default='NoName', max_length=127),
            preserve_default=False,
        ),
    ]
