# Generated by Django 5.1.7 on 2025-03-19 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0013_remote_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='task',
        ),
        migrations.AddField(
            model_name='job',
            name='dstFs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_dstFs', to='sync.remote'),
        ),
        migrations.AddField(
            model_name='job',
            name='srcFs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_srcFs', to='sync.remote'),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('sync/copy', 'copy')], default='sync/copy', max_length=127),
        ),
        migrations.AlterField(
            model_name='remote',
            name='type',
            field=models.CharField(choices=[('s3', 'S3'), ('sftp', 'SFTP')], max_length=127),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('cron', models.CharField(max_length=127)),
                ('type', models.CharField(choices=[('sync/copy', 'copy')], default='sync/copy', max_length=127)),
                ('dstFs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_dstfFs', to='sync.remote')),
                ('srcFs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_srcfFs', to='sync.remote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='sync.schedule'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
