# Generated by Django 5.1.7 on 2025-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_dailystatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailystatistics',
            old_name='bandwidth_consumed',
            new_name='bytes',
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='serverSideCopyBytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystatistics',
            name='serverSideMoveBytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
