# Generated by Django 5.1.7 on 2025-03-21 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_rename_bandwidth_consumed_dailystatistics_bytes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobRunStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('speed', models.IntegerField()),
                ('speedServerSideCopy', models.IntegerField()),
                ('speedServerSideMove', models.IntegerField()),
                ('transferSpeed', models.IntegerField()),
                ('transferSpeedServerSideCopy', models.IntegerField()),
                ('transferSpeedServerSideMove', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.job')),
            ],
        ),
    ]
