# Generated by Django 5.1.7 on 2025-03-22 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0017_jobrunstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 2, 13, 23, 521964, tzinfo=datetime.timezone.utc)),
        ),
    ]
