# Generated by Django 5.1.7 on 2025-03-22 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0018_alter_jobrunstatistics_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
