# Generated by Django 5.1.7 on 2025-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0019_alter_jobrunstatistics_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='transferSpeed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='transferSpeedServerSideCopy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='transferSpeedServerSideMove',
            field=models.FloatField(),
        ),
    ]
