# Generated by Django 5.1.7 on 2025-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0021_jobrunstatistics_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='checks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='speedServerSideCopy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='speedServerSideMove',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='transferSpeedServerSideCopy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrunstatistics',
            name='transferSpeedServerSideMove',
            field=models.FloatField(default=0),
        ),
    ]
