# Generated by Django 5.1.7 on 2025-03-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_continent_server_country_server_data_cap_and_more'),
        ('sync', '0022_alter_jobrunstatistics_checks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.server'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.server'),
        ),
    ]
