# Generated by Django 5.1.7 on 2025-03-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_continent_server_country_server_data_cap_and_more'),
        ('sync', '0023_job_server_schedule_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dstFsPath',
            field=models.CharField(default='/', max_length=127),
        ),
        migrations.AddField(
            model_name='job',
            name='srcFsPath',
            field=models.CharField(default='/', max_length=127),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dstFsPath',
            field=models.CharField(default='/', max_length=127),
        ),
        migrations.AddField(
            model_name='schedule',
            name='srcFsPath',
            field=models.CharField(default='/', max_length=127),
        ),
        migrations.AlterField(
            model_name='job',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='servers.server'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='servers.server'),
        ),
    ]
