# Generated by Django 5.1.7 on 2025-03-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0024_job_dstfspath_job_srcfspath_schedule_dstfspath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='options',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='options',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('sync/copy', [('display', 'Copy'), ('description', 'Copy files from source to destination, skipping identical files')]), ('sync/sync', [('display', 'Sync'), ('description', 'Make source and dest identical, modifying destination only')]), ('sync/move', [('display', 'Move'), ('description', 'Move files from source to destination')])], default='sync/copy', max_length=127),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('sync/copy', [('display', 'Copy'), ('description', 'Copy files from source to destination, skipping identical files')]), ('sync/sync', [('display', 'Sync'), ('description', 'Make source and dest identical, modifying destination only')]), ('sync/move', [('display', 'Move'), ('description', 'Move files from source to destination')])], default='sync/copy', max_length=127),
        ),
    ]
