# Generated by Django 5.1.7 on 2025-03-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0025_job_options_schedule_options_alter_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='options',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
