# Generated by Django 5.1.7 on 2025-03-27 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sync', '0026_alter_job_options_alter_schedule_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='dstFs',
        ),
        migrations.RemoveField(
            model_name='job',
            name='srcFs',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dstFs',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='srcFs',
        ),
        migrations.AddField(
            model_name='job',
            name='dstFs_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_dstFs_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='job',
            name='dstFs_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='srcFs_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_srcFs_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='job',
            name='srcFs_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dstFs_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_dstFs_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dstFs_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='srcFs_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schdule_srcFs_content_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='srcFs_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('remotes', models.ManyToManyField(to='sync.remote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
