# Generated by Django 5.1.7 on 2025-03-31 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0027_remove_job_dstfs_remove_job_srcfs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('sync/copy', 'Copy'), ('sync/sync', 'Sync'), ('sync/move', 'Move')], default='sync/copy', max_length=127),
        ),
        migrations.AlterField(
            model_name='remote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('sync/copy', 'Copy'), ('sync/sync', 'Sync'), ('sync/move', 'Move')], default='sync/copy', max_length=127),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='union',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to=settings.AUTH_USER_MODEL),
        ),
    ]
