# Generated by Django 5.1.7 on 2025-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_contact'),
        ('sync', '0028_alter_job_type_alter_remote_user_alter_schedule_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='notifications.contact'),
        ),
    ]
