# Generated by Django 5.1.7 on 2025-04-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_contact'),
        ('sync', '0029_job_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='notifications.contact'),
        ),
    ]
