# Generated by Django 5.1.7 on 2025-04-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0030_schedule_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailystatistics',
            old_name='errored_jobs',
            new_name='failed_jobs',
        ),
    ]
